/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug 18 2014, 17:12:05                              *
*        (c) 2014 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "main_dispaly.h"
#include "imagebmp.h"
#include "device_info.h"
#include "onenet.h"
#include "string.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0   (GUI_ID_USER + 0x00)
#define ID_MULTIPAGE_0   (GUI_ID_USER + 0x01)
#define ID_SPINBOX_0   (GUI_ID_USER + 0x02)
#define ID_BUTTON_0   (GUI_ID_USER + 0x03)
#define ID_BUTTON_1   (GUI_ID_USER + 0x04)
#define ID_TEXT_0   (GUI_ID_USER + 0x05)
#define ID_TEXT_1   (GUI_ID_USER + 0x06)
#define ID_TEXT_2   (GUI_ID_USER + 0x07)
#define ID_TEXT_3   (GUI_ID_USER + 0x08)
#define ID_TEXT_4   (GUI_ID_USER + 0x09)
#define ID_TEXT_5   (GUI_ID_USER + 0x0a)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
static GUI_BITMAP buttonbmp_tab[2];
static uint8_t is_button_press = 0;
static uint8_t button_status[2] = {1,1};

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Window", ID_FRAMEWIN_0, 0, 0, 320, 240, 0, 0x64, 0 },
  { MULTIPAGE_CreateIndirect, "Multipage", ID_MULTIPAGE_0, 0, 25, 310, 120, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "fenrate", ID_SPINBOX_0, 230, 150, 80, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button1", ID_BUTTON_0, 60, 150, 50, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button2", ID_BUTTON_1, 60, 180, 50, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "relay", ID_TEXT_0, 0, 150, 60, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "motor", ID_TEXT_1, 0, 180, 60, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "main", ID_TEXT_2, 100, 0, 100, 24, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "fen", ID_TEXT_3, 160, 150, 64, 45, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "time", ID_TEXT_4, 10, 210, 176, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "wifi", ID_TEXT_5, 192, 210, 120, 20, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
extern WM_HWIN Createpage1(void);
extern WM_HWIN Createpage2(void);
extern WM_HWIN Createpage3(void);
extern WM_HWIN Createpage4(void);
extern WM_HWIN Createpage5(void);
extern WM_HWIN Createpage6(void);
extern WM_HWIN Createpage7(void);
// USER START (Optionally insert additional static code)
// USER END
static void buff_display(WM_MESSAGE * pMsg)
{
	char disp_dat[20];
	WM_HWIN hItem;
	int value;
	uint16_t hour,minute,sec;
	static uint8_t display_update_flag = 0;


	if(button_status[0] != RELAY1_KEY)
	{
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		BUTTON_SetBitmapEx(hItem,0,&buttonbmp_tab[button_status[0] & 0x01],0,0);
		button_status[0] = RELAY1_KEY; 
	}
	
	if(button_status[1] != RELAY2_KEY)
	{
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetBitmapEx(hItem,0,&buttonbmp_tab[button_status[1] & 0x01],0,0);
		button_status[1] = RELAY2_KEY; 
	}
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);	
	value =  SPINBOX_GetValue(hItem);
	if(deviceStatus.motor_rate != value && !is_button_press)
	{
		SPINBOX_SetValue(hItem,deviceStatus.motor_rate);		
	}
	
	
	if(warning_info.enable_flag & TIMING_MAX_SWITCH)
	{
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);  		
		hour = deviceStatus.timing_sec/3600;
		minute = (deviceStatus.timing_sec%3600)/60;
		sec = deviceStatus.timing_sec%60;	
		rt_sprintf(disp_dat,"剩余时间:%d时%d分%d秒",hour,minute,sec);
		display_update_flag |= 0x01;
		TEXT_SetText(hItem, disp_dat);			
	}
	else if(display_update_flag & 0x01)
	{
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);  			
		display_update_flag &= 0xfe;
		memcpy(disp_dat,"未开启定时",sizeof("未开启定时"));	
		TEXT_SetText(hItem, disp_dat);		
	}
	

	
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);

	if(oneNetInfo.netWork && !(display_update_flag & 0x02))
	{
		TEXT_SetText(hItem, "网络状态:已连接");	
		display_update_flag |= 0x02;
	}
    else if(!oneNetInfo.netWork && display_update_flag & 0x02)
	{
		display_update_flag &= 0xfd;
		TEXT_SetText(hItem, "网络状态:断开");
	}
	/*刷新0页面显示*/
	hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIPAGE_0);  
	value = MULTIPAGE_GetSelection(hItem);
	if(value == 0)
	{
		WM_InvalidateWindow(MULTIPAGE_GetWindow(hItem,value));
	}	
}
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  uint8_t value;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'main'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTitleVis(hItem, 0);	  
	FRAMEWIN_SetClientColor(hItem,GUI_WHITE);
    //
    // Initialization of 'Multipage'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIPAGE_0);
    MULTIPAGE_AddEmptyPage(hItem, Createpage1(), "总信息");
	MULTIPAGE_AddEmptyPage(hItem, Createpage2(), "温度曲线");
	MULTIPAGE_AddEmptyPage(hItem, Createpage3(), "湿度曲线");
	MULTIPAGE_AddEmptyPage(hItem, Createpage4(), "风速曲线");
    MULTIPAGE_AddEmptyPage(hItem, Createpage5(), "定时");
	MULTIPAGE_AddEmptyPage(hItem, Createpage6(), "设置");
    MULTIPAGE_AddEmptyPage(hItem, Createpage7(), "Wifi");
	MULTIPAGE_SetFont(hItem,&GUI_FontHZ12);
	MULTIPAGE_SetBkColor(hItem,0x00c0c0c0,MULTIPAGE_CI_DISABLED);
	MULTIPAGE_SetBkColor(hItem,0x00ddb49b,MULTIPAGE_CI_ENABLED);
//	MULTIPAGE_DisablePage(hItem,5);
//	MULTIPAGE_DisablePage(hItem,6);
	MULTIPAGE_SelectPage(hItem,0);
  
    //
    // Initialization of '风速显示'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
    SPINBOX_SetFont(hItem, GUI_FONT_20_1);
    SPINBOX_SetRange(hItem,1,99);
	SPINBOX_SetValue(hItem,Read_PWM_Arr());

	//初始化BUTTON0
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
	BUTTON_SetBitmapEx(hItem,0,&buttonbmp_tab[0],0,0);
	BUTTON_SetText(hItem, "");
	
	//初始化BUTTON1
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
	BUTTON_SetBitmapEx(hItem,0,&buttonbmp_tab[0],0,0);
	BUTTON_SetText(hItem, "");	
	//
    // Initialization of 'relay'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_BLUE);
	TEXT_SetFont(hItem,&GUI_FontHZ16);
    TEXT_SetText(hItem, "加热:");
    //
    // Initialization of 'motor'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_BLUE);
	TEXT_SetFont(hItem,&GUI_FontHZ16);	
    TEXT_SetText(hItem, "风扇:");
    //
    // Initialization of 'main'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_RED);
    TEXT_SetText(hItem, "皮皮鞋盒");
    TEXT_SetFont(hItem, &GUI_FontHZ24);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, &GUI_FontHZ16);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetTextColor(hItem, GUI_BLUE);	
    TEXT_SetText(hItem, "风扇速度");
    //
    // Initialization of 'time'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, &GUI_FontHZ16);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_BLACK);
    TEXT_SetText(hItem, "剩余时间:4小时59分59秒");
    //
    // Initialization of 'wifi'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, &GUI_FontHZ16);
    TEXT_SetTextAlign(hItem, EDIT_CF_RIGHT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_BLACK);
    TEXT_SetText(hItem, "网络状态:断开");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_MULTIPAGE_0: // Notifications sent by 'Multipage'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_0: // Notifications sent by 'Spinbox'
		hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
	
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
		is_button_press = 1;
	  
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
		is_button_press = 0;
		//SPINBOX_SetValue
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
		is_button_press = 0;
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
		 value =  SPINBOX_GetValue(hItem);
		 deviceStatus.motor_rate = value;
	     SET_PWM_Arr(value);
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Button'
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		BUTTON_SetBitmapEx(hItem,0,&buttonbmp_tab[RELAY1_KEY & 0x01],0,0);
		RELAY1_KEY =~RELAY1_KEY;
	  	LED_1_KEY =~LED_1_KEY;		//LED1反转
		button_status[0] = RELAY1_KEY;
		deviceStatus.relay_key = ~RELAY1_KEY;	  
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button'
		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
	switch(NCode) {

      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		BUTTON_SetBitmapEx(hItem,0,&buttonbmp_tab[RELAY2_KEY&0x01],0,0);	
	    RELAY2_KEY =~RELAY2_KEY;
	  	LED_2_KEY =~LED_2_KEY;							//LED1反转
		button_status[1] = RELAY2_KEY; 
		deviceStatus.motor_key = ~RELAY2_KEY;
		// USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  case WM_TIMER:
	WM_RestartTimer(pMsg -> Data.v,1000);//重启定时器，因为窗口定时器是单次的
    buff_display(pMsg);
	break;	
	
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Main_Display_Create(void);

WM_HWIN Main_Display_Create(void) 
{
	WM_HWIN hWin;
	buttonbmp_tab[0] = bmp_button_off;
	buttonbmp_tab[1] = bmp_button_on;
	
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	WM_CreateTimer(WM_GetClientWindow(hWin),0,1000,0);
	
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/

