/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug 18 2014, 17:12:05                              *
*        (c) 2014 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "device_info.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_1     (GUI_ID_USER + 0x20)
#define ID_GRAPH_20     (GUI_ID_USER + 0x21)
#define ID_CHECKBOX_20     (GUI_ID_USER + 0x22)
#define ID_CHECKBOX_21     (GUI_ID_USER + 0x23)
#define ID_CHECKBOX_22     (GUI_ID_USER + 0x24)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
static GRAPH_DATA_Handle  tempData[3];                         /* 用于 GRAPH_DATA 类型的句柄 */
static GRAPH_SCALE_Handle tempVscale;
static GUI_COLOR _aColor[3] = {GUI_LIGHTGREEN,GUI_LIGHTRED,GUI_LIGHTYELLOW};/* 三种曲线的颜色值 */

/*********************************************************************
*
*       _aDialogpage2Create
*/
static const GUI_WIDGET_CREATE_INFO _aDialogpage2Create[] = {
  { WINDOW_CreateIndirect, "page2", ID_WINDOW_1, 0, 0, 310, 120, 0, 0x0, 0 },
  { GRAPH_CreateIndirect, "alltemp", ID_GRAPH_20, 0, 24, 306, 76, 0, 0x0, 2 },
  { CHECKBOX_CreateIndirect, "temp1", ID_CHECKBOX_20, 20, 2, 80, 20, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "temp2", ID_CHECKBOX_21, 110, 2, 80, 20, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "temp3", ID_CHECKBOX_22, 200, 2, 80, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbpage2Dialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
	  
  case WM_INIT_DIALOG:
	  
  	hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_DARKCYAN);
  
    hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_20);
    GRAPH_SetBorder(hItem,20, 2, 2, 2);
	GRAPH_SetGridDistX(hItem,20);	//网格X大小
	GRAPH_SetGridDistY(hItem,10);	//网格Y大小
	GRAPH_SetGridVis(hItem,1);		//显示网格
//	GRAPH_DATA_YT_SetOffY(hItem,-10);	//Y轴数据的偏移
//	GRAPH_SetVSizeY(hItem,80);
	
	tempVscale = GRAPH_SCALE_Create(2,GUI_TA_HORIZONTAL,GRAPH_SCALE_CF_VERTICAL,20);
	GRAPH_SCALE_SetFont(tempVscale,GUI_FONT_8_ASCII);
	GRAPH_SCALE_SetTextColor(tempVscale,GUI_BLUE);
	GRAPH_AttachScale(hItem,tempVscale); 
	
//	tempHscale = GRAPH_SCALE_Create(2,GUI_TA_HORIZONTAL|GUI_TA_TOP,GRAPH_SCALE_CF_HORIZONTAL,40);
//	GRAPH_SCALE_SetFont(tempHscale,GUI_FONT_8_ASCII);
//	GRAPH_SCALE_SetTextColor(tempHscale,GUI_BLUE);
//	GRAPH_AttachScale(hItem,tempHscale); 
  

	tempData[0] = GRAPH_DATA_YT_Create(_aColor[0], 300, 0, 0);
	tempData[1] = GRAPH_DATA_YT_Create(_aColor[1], 300, 0, 0);
	tempData[2] = GRAPH_DATA_YT_Create(_aColor[2], 300, 0, 0);
//	/* 为绘图控件添加数据对象 */
//	GRAPH_AttachData(hItem, tempData[0]);
//	GRAPH_AttachData(hItem, tempData[1]);
//	GRAPH_AttachData(hItem, tempData[2]);
	WIDGET_SetEffect(hItem, &WIDGET_Effect_None);  
    //
    // Initialization of 'temp1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_20);
    CHECKBOX_SetText(hItem, "温度1");
    CHECKBOX_SetTextColor(hItem, _aColor[0]);
    CHECKBOX_SetFont(hItem,&GUI_FontHZ12);
	CHECKBOX_SetState(hItem,1);
    //
    // Initialization of 'temp2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_21);
    CHECKBOX_SetText(hItem, "温度2");
    CHECKBOX_SetTextColor(hItem, _aColor[1]);
    CHECKBOX_SetFont(hItem,&GUI_FontHZ12);  
	CHECKBOX_SetState(hItem,1);
	//
    // Initialization of 'temp3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_22);
    CHECKBOX_SetText(hItem, "温度3");
    CHECKBOX_SetTextColor(hItem, _aColor[2]);
    CHECKBOX_SetFont(hItem,&GUI_FontHZ12);
	CHECKBOX_SetState(hItem,1);
	// USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_CHECKBOX_20: // Notifications sent by 'temp1'
      switch(NCode) {		  
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_20);
		if(CHECKBOX_IsChecked(hItem))
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_20);
			GRAPH_AttachData(hItem,tempData[0]);
		}
		else
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_20);
			GRAPH_DATA_YT_Clear(tempData[0]);
			GRAPH_DetachData(hItem,tempData[0]);
		}
		// USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_21: // Notifications sent by 'temp2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_21);
		if(CHECKBOX_IsChecked(hItem))
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_20);
			GRAPH_AttachData(hItem,tempData[1]);
		}
		else
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_20);
			GRAPH_DATA_YT_Clear(tempData[1]);
			GRAPH_DetachData(hItem,tempData[1]);			
		}
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_22: // Notifications sent by 'temp3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_22);
		if(CHECKBOX_IsChecked(hItem))
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_20);
			GRAPH_AttachData(hItem,tempData[2]);
		}
		else
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_20);
			GRAPH_DATA_YT_Clear(tempData[2]);
			GRAPH_DetachData(hItem,tempData[2]);		
		}
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
	case WM_TIMER:
		if(WM_GetTimerId(pMsg->Data.v) == 0)
		{
			GRAPH_DATA_YT_AddValue(tempData[0], dht11Info.tempreture_1);
			GRAPH_DATA_YT_AddValue(tempData[1], dht11Info.tempreture_2);
			GRAPH_DATA_YT_AddValue(tempData[2], gy906Info.temp_to);
			/* 重启定时器 */
			WM_RestartTimer(pMsg->Data.v, 1000);
		}
		break;	
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Createpage2
*/
WM_HWIN Createpage2(void);
WM_HWIN Createpage2(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogpage2Create, GUI_COUNTOF(_aDialogpage2Create), _cbpage2Dialog, WM_HBKWIN, 0, 0);
	/* 创建两个定时器 */
	WM_CreateTimer(hWin, 			/* 接受信息的窗口的句柄 */
				   0, 	         	/* 用户定义的Id。如果不对同一窗口使用多个定时器，此值可以设置为零。 */
				   1000,           	/* 周期，此周期过后指定窗口应收到消息*/
				   0);	
	
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
