/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug 18 2014, 17:12:05                              *
*        (c) 2014 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "device_info.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_5     (GUI_ID_USER + 0x60)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogpage6Create
*/
static const GUI_WIDGET_CREATE_INFO _aDialogpage6Create[] = {
  { WINDOW_CreateIndirect, "page6", ID_WINDOW_5, 0, 0, 310, 120, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbpage6Dialog
*/
static void _cbpage6Dialog(WM_MESSAGE * pMsg) {
  // USER START (Optionally insert additional variables)
  // USER END
  WM_HWIN hItem;
	
  switch (pMsg->MsgId) {
  case WM_PAINT:
	GUI_SetColor(GUI_BLACK);
	GUI_SetFont(&GUI_FontHZ12);
  
	GUI_DispStringAt("   此页面未完善! ",0,3);
    GUI_DispString("   下面设置连接的Wifi的方法");
    GUI_DispStringAt("1.使用串口连接 115200",5,6+12);
    GUI_DispStringAt("2.一次发送下面内容",5,9+12*2);
    GUI_DispString("   \\r\\n为回车符 不需要输入!");
    GUI_DispStringAt("SSID:Wifi名称\\r\\n",5,12+12*3);
    GUI_DispString("   PSWD:Wifi密码\\r\\n");
    GUI_DispStringAt("DEVID:35852269\\r\\n",5,15+12*4);
    GUI_DispStringAt("APIKEY:LwithCI7=NoIXIplbjRdDxe118g=\\r\\n",5,18+12*5);
  
  break;
  case WM_INIT_DIALOG:
	hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_DARKCYAN);
	GUI_SetColor(GUI_BLACK);
  break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Createpage6
*/
WM_HWIN Createpage6(void);
WM_HWIN Createpage6(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogpage6Create, GUI_COUNTOF(_aDialogpage6Create), _cbpage6Dialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
