/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug 18 2014, 17:12:05                              *
*        (c) 2014 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "device_info.h"
#include "onenet.h"
#include "net_device.h"	//网络设备应用层
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_6   (GUI_ID_USER + 0x70)
#define ID_TEXT_70   (GUI_ID_USER + 0x71)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogpage7Create
*/
static const GUI_WIDGET_CREATE_INFO _aDialogpage7Create[] = {
  { WINDOW_CreateIndirect, "page7", ID_WINDOW_6, 0, 0, 310, 120, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "p7info", ID_TEXT_70, 30, 20, 200, 60, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbpage7Dialog
*/
static void _cbpage7Dialog(WM_MESSAGE * pMsg) {
  // USER START (Optionally insert additional variables)
  WM_HWIN hItem;
	
  switch (pMsg->MsgId) {
  case WM_PAINT:
	GUI_SetColor(GUI_BLACK);
	GUI_SetFont(&GUI_FontHZ12);
	GUI_DispStringAt("WiFi名称:",0,3);
	GUI_DispString(netDeviceInfo.staName);
	GUI_DispStringAt("WiFi密码:",0,6+12);
	GUI_DispString(netDeviceInfo.staPass);  
	GUI_DispStringAt("DEVID::",0,9+12*2);
	GUI_DispString(oneNetInfo.devID);  
	GUI_DispStringAt("APIKEY:",0,12+12*3);
	GUI_DispString(oneNetInfo.apiKey);  
  case WM_INIT_DIALOG:
	hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_DARKCYAN);
	GUI_SetColor(GUI_BLACK);	
    break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Createpage7
*/
WM_HWIN Createpage7(void);
WM_HWIN Createpage7(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogpage7Create, GUI_COUNTOF(_aDialogpage7Create), _cbpage7Dialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
