/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug 18 2014, 17:12:05                              *
*        (c) 2014 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "device_info.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x10)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogpag1Create[] = {
  { WINDOW_CreateIndirect, "page1", ID_WINDOW_0, 0, 0, 310, 120, 0, 0x0, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbPage1Dialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  
  case WM_PAINT:
	GUI_SetColor(GUI_BLACK);
	GUI_SetFont(&GUI_FontHZ16);
	GUI_DispStringAt("温度1:",5,5);
  	GUI_SetColor(GUI_BLUE);
	GUI_DispFloat(dht11Info.tempreture_1,5);
	GUI_DispString("'C");
  	GUI_SetColor(GUI_BLACK);
	GUI_DispString("      湿度1:");
    GUI_SetColor(GUI_BLUE);
	GUI_DispDec(dht11Info.humidity_1,2);
	GUI_DispString("%");

	GUI_SetColor(GUI_BLACK);
    GUI_DispStringAt("温度2:",5,10+16);
    GUI_SetColor(GUI_BLUE);
	GUI_DispFloat(dht11Info.tempreture_2,5);
	GUI_DispString("'C");
  
	GUI_SetColor(GUI_BLACK);  
	GUI_DispString("      湿度2:");
	GUI_SetColor(GUI_BLUE);
    GUI_DispDec(dht11Info.humidity_2,2);	
	GUI_DispString("%");

	GUI_SetColor(GUI_BLACK);
	GUI_DispStringAt("环境温度:",5,15+16*2);
	GUI_SetColor(GUI_BLUE);
	GUI_DispFloat(gy906Info.temp_ta,5);
	GUI_DispString("'C");

	GUI_SetColor(GUI_BLACK);
	GUI_DispString("   物体温度:");
	GUI_SetColor(GUI_BLUE);
	GUI_DispFloat(gy906Info.temp_to,5);	
	GUI_DispString("'C");

	GUI_SetColor(GUI_BLACK);
	GUI_DispStringAt("电机速度:",5,20+16*3);
	GUI_SetColor(GUI_BLUE);
	GUI_DispDec(deviceStatus.motor_rate,2);
	GUI_DispString("%");

	GUI_SetColor(GUI_BLACK);
	GUI_DispString("       继电器:");
	GUI_SetColor(GUI_BLUE);
	if(deviceStatus.relay_key)
	{
		GUI_DispString("开");
	}
	else
	{
		GUI_DispString("关");
	}
	break;
//  case WM_TIMER:
//	WM_RestartTimer(pMsg -> Data.v,1000);//重启定时器，因为窗口定时器是单次的
//	WM_InvalidateWindow(pMsg -> hWin);	  
//	break;
  case WM_INIT_DIALOG:
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, 0x00ffbbdd);
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Createpage1
*/
WM_HWIN Createpage1(void);
WM_HWIN Createpage1(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogpag1Create, GUI_COUNTOF(_aDialogpag1Create), _cbPage1Dialog, WM_HBKWIN, 0, 0);
//  WM_CreateTimer(hWin,0,1000,0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
