/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug 18 2014, 17:12:05                              *
*        (c) 2014 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "device_info.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_3     (GUI_ID_USER + 0x40)
#define ID_GRAPH_40     (GUI_ID_USER + 0x41)
#define ID_CHECKBOX_40     (GUI_ID_USER + 0x42)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
static GRAPH_DATA_Handle  FrateData;                    /* 用于 GRAPH_DATA 类型的句柄 */
static GRAPH_SCALE_Handle FrateVscale;					/*标度句柄*/
static GUI_COLOR 		FrateColor = 0x0080ff;				/* 曲线的颜色值 */
// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogpage4Create
*/
static const GUI_WIDGET_CREATE_INFO _aDialogpage4Create[] = {
  { WINDOW_CreateIndirect, "page4", ID_WINDOW_3, 0, 0, 310, 120, 0, 0x0, 0 },
  { GRAPH_CreateIndirect, "p4rate", ID_GRAPH_40, 0, 24, 306, 76, 0, 0x0, 2 },
  { CHECKBOX_CreateIndirect, "p4rate", ID_CHECKBOX_40, 120, 2, 80, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbpage4Dialog
*/
static void _cbpage4Dialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
	//
	// Initialization of 'alltemp'
	//
	hItem = pMsg->hWin;
	WINDOW_SetBkColor(hItem, GUI_DARKCYAN);
    // Initialization of 'p4rate'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_40);
  
    GRAPH_SetBorder(hItem,20, 2, 2, 2);
	GRAPH_SetGridDistX(hItem,20);	//网格X大小
	GRAPH_SetGridDistY(hItem,10);	//网格Y大小
	GRAPH_SetGridVis(hItem,1);		//显示网格
	GRAPH_SetVSizeY(hItem,100);
	
	FrateVscale = GRAPH_SCALE_Create(2,GUI_TA_HORIZONTAL,GRAPH_SCALE_CF_VERTICAL,20);
	GRAPH_SCALE_SetFont(FrateVscale,GUI_FONT_8_ASCII);
	GRAPH_SCALE_SetTextColor(FrateVscale,GUI_BLUE);
	GRAPH_AttachScale(hItem,FrateVscale); 
 
	FrateData = GRAPH_DATA_YT_Create(FrateColor, 300, 0, 0);
	WIDGET_SetEffect(hItem, &WIDGET_Effect_None);  
    // Initialization of 'p4rate'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_40);
    CHECKBOX_SetText(hItem, "风速");
    CHECKBOX_SetTextColor(hItem, FrateColor);
  	CHECKBOX_SetFont(hItem,&GUI_FontHZ12); 
	CHECKBOX_SetState(hItem,1);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_CHECKBOX_40: // Notifications sent by 'p4rate'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_40);
		if(CHECKBOX_IsChecked(hItem))
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_40);
			GRAPH_AttachData(hItem,FrateData);
		}
		else
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_40);
			GRAPH_DATA_YT_Clear(FrateData);
			GRAPH_DetachData(hItem,FrateData);	
		}
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
	case WM_TIMER:
		if(WM_GetTimerId(pMsg->Data.v) == 0)
		{
			GRAPH_DATA_YT_AddValue(FrateData, deviceStatus.motor_rate);
			/* 重启定时器 */
			WM_RestartTimer(pMsg->Data.v, 1000);
		}
		break;	
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Createpage4
*/
WM_HWIN Createpage4(void);
WM_HWIN Createpage4(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogpage4Create, GUI_COUNTOF(_aDialogpage4Create), _cbpage4Dialog, WM_HBKWIN, 0, 0);
	/* 创建一个定时器 */
	WM_CreateTimer(hWin, 		/* 接受信息的窗口的句柄 */
				   0, 	        /* 用户定义的Id。如果不对同一窗口使用多个定时器，此值可以设置为零。 */
				   1000,        /* 周期，此周期过后指定窗口应收到消息*/
				   0);	
	
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
